# Generated by Django 3.0.6 on 2020-06-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200601_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='activateusertoken',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
