version: '3.7'
   
services:
  postgres_db:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - media_volume:/app/Gamein/media
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  web:
    build: .
    container_name: web
    restart: always
    command: >
      sh -c "
        ./manage.py makemigrations;
        ./manage.py migrate;
        ./manage.py collectstatic --noinput;
        gunicorn --bind=0.0.0.0:8181 --timeout=90 --workers=10 --preload gamein_backend.wsgi:application; 
       "
    volumes:
      - static_volume:/app/Gamein/static
      - media_volume:/app/Gamein/media
    ports:
      - 8181:8181
    depends_on:
      - postgres_db
    env_file:
      - .env
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - static_volume:/app/Gamein/static
      - media_volume:/app/Gamein/media
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
