# Generated by Django 3.0.6 on 2020-05-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('family_name', models.CharField(max_length=64)),
                ('picture', models.ImageField(upload_to='staff_pictures')),
                ('role', models.CharField(max_length=20)),
                ('linked_in_url', models.URLField()),
            ],
        ),
    ]
