# Generated by Django 3.0.7 on 2020-06-09 11:23

import apps.homepage.models
import apps.homepage.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('context', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('persian_date', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('countdownable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoter', models.CharField(default='ناشناس', max_length=100)),
                ('context', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField()),
                ('icon', models.ImageField(storage=apps.homepage.storage.OverwriteStorage(), upload_to=apps.homepage.models.Social.upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sponsor_class', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=100)),
                ('picture', models.ImageField(upload_to=apps.homepage.models.Sponsor.upload_path)),
                ('site_url', models.URLField(verbose_name='WebSite')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('stat', models.IntegerField()),
                ('icon', models.ImageField(upload_to='stat_icons')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(storage=apps.homepage.storage.OverwriteStorage(), upload_to=apps.homepage.models.Video.upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('award', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='family_name',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='staff',
            name='linked_in_url',
            field=models.URLField(blank=True, verbose_name='Linked-in'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='picture',
            field=models.ImageField(blank=True, default='staff_pictures/profile.jpg', storage=apps.homepage.storage.OverwriteStorage(), upload_to=apps.homepage.models.Staff.upload_path),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='StaffTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('head', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_count', models.IntegerField()),
                ('about', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homepage.About')),
                ('events', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homepage.Event')),
                ('faq', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homepage.FAQ')),
                ('quotes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homepage.Quote')),
                ('socials', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homepage.Social')),
                ('sponsors', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homepage.Sponsor')),
                ('staffs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homepage.Staff')),
                ('statistics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homepage.Statistics')),
                ('videos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homepage.Video')),
                ('winners', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homepage.Winner')),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.StaffTeam'),
        ),
    ]
