# Generated by Django 3.0.6 on 2020-05-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='team',
            field=models.CharField(choices=[('Site', 'Site'), ('Idea', 'Idea'), ('others', 'Others')], max_length=64),
        ),
    ]
