# Generated by Django 3.0.6 on 2020-05-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoter', models.CharField(max_length=100)),
                ('context', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='winner',
            name='color',
            field=models.CharField(default='white', max_length=50),
            preserve_default=False,
        ),
    ]
