# Generated by Django 3.0.6 on 2020-05-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20200528_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField()),
                ('icon', models.ImageField(upload_to='social_icons')),
            ],
        ),
        migrations.AlterField(
            model_name='quote',
            name='quoter',
            field=models.CharField(default='ناشناس', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='linked_in_url',
            field=models.URLField(blank=True, verbose_name='Linked-in'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='picture',
            field=models.ImageField(blank=True, default='staff_pictures/profile.jpg', upload_to='staff_pictures'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
