# Generated by Django 3.0.7 on 2020-06-09 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_auto_20191227_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='document',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='resources.Document'),
        ),
    ]
