# Generated by Django 3.0.6 on 2020-06-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='Values',
            new_name='values_of_fields',
        ),
    ]
