# Generated by Django 3.0.6 on 2020-05-31 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='emails.EmailTemplate')),
            ],
        ),
        migrations.DeleteModel(
            name='EmailContent',
        ),
    ]
