# Generated by Django 3.0.6 on 2020-06-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplatefield',
            name='field_value',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='recipients',
            field=models.ManyToManyField(blank=True, to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='html',
            field=models.TextField(),
        ),
    ]
