# Generated by Django 3.0.6 on 2020-06-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20200604_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplatefield',
            name='field_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
