# Generated by Django 3.0.6 on 2020-06-01 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0002_auto_20200601_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('values_of_fields', models.TextField()),
                ('html_context', models.TextField()),
                ('text_context', models.TextField()),
                ('recipients', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='emails.EmailTemplate')),
            ],
        ),
        migrations.DeleteModel(
            name='Email',
        ),
    ]
