# Generated by Django 3.0.6 on 2020-06-09 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_auto_20200604_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.EmailTemplate'),
        ),
    ]
