# Generated by Django 3.0.6 on 2020-06-03 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_auto_20200601_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplateKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_type', models.CharField(choices=[('UN', 'user.name'), ('UU', 'user.university')], default=None, max_length=3)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.EmailTemplate')),
            ],
        ),
    ]
